language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
    # CPython
  - "nightly"
    # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
branches:
  only:
    - feat-travis-ci
env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - SENTRY_LIGHT_BUILD=1
    - SENTRY_SKIP_BACKEND_VALIDATION=1
    - CXX=g++-4.8
install:
  - pip install -r requirements.txt
  - python frequency.py
script:
  - make travis-lint-$TEST_SUITE
  - make travis-test-$TEST_SUITE
matrix:
include:
  - python: "nightly"
    env: TEST_SUITE=mysql DB=mysql
    services:
      - memcached
      - mysql
      - redis
